//! Conformance for `modhash-bmp`: the fixture files under
//! `tests/fixtures/` are generated byte-by-byte by
//! `tests/fixtures/gen_fixtures.py` (see `PROVENANCE.md`), and every
//! builder in this file reimplements the same generator in Rust. Tests
//! pin the decoded pixels, then pin builder output to fixture bytes so
//! neither side can drift from the other.

use pith_digest::{Error, SplitMix64};
use pith_image::bmp::{Compression, decode, info};
use pith_image::raster::{Image, Rgba};

// ---- byte-level fixture builders (mirror gen_fixtures.py) ------------------

/// Writes `v` little-endian into `out`.
fn le16(out: &mut Vec<u8>, v: u16) {
    out.extend_from_slice(&v.to_le_bytes());
}
fn le32(out: &mut Vec<u8>, v: u32) {
    out.extend_from_slice(&v.to_le_bytes());
}

struct BmpArgs<'a> {
    w: i32,
    h: i32,
    bpp: u16,
    compression: u32,
    dib_size: u32,
    /// R,G,B,A channel masks. For a 40-byte DIB they are written inline
    /// after the header; for V4/V5 they live inside the header at +40.
    masks: Option<[u32; 4]>,
    /// Palette entries as `(r, g, b)`; written as `b g r 0`.
    palette: Option<Vec<[u8; 3]>>,
    colors_used: u32,
    pixel: &'a [u8],
    /// Bytes of `0xAA` padding inserted between structures and pixels.
    pad: usize,
}

/// Assembles a BMP file exactly the way `gen_fixtures.py` does.
fn build_bmp(a: &BmpArgs) -> Vec<u8> {
    let has_masks = a.compression == 3 || a.compression == 6;
    let mut dib = Vec::with_capacity(a.dib_size as usize);
    le32(&mut dib, a.dib_size);
    le32(&mut dib, a.w as u32);
    le32(&mut dib, a.h as u32);
    le16(&mut dib, 1); // planes
    le16(&mut dib, a.bpp);
    le32(&mut dib, a.compression);
    le32(&mut dib, a.pixel.len() as u32); // biSizeImage
    le32(&mut dib, 2835);
    le32(&mut dib, 2835);
    le32(&mut dib, a.colors_used);
    le32(&mut dib, 0);
    dib.resize(a.dib_size as usize, 0);
    if a.dib_size >= 108 && has_masks {
        let m = a
            .masks
            .unwrap_or([0x00FF_0000, 0x0000_FF00, 0x0000_00FF, 0xFF00_0000]);
        for (i, v) in m.iter().enumerate() {
            dib[40 + i * 4..44 + i * 4].copy_from_slice(&v.to_le_bytes());
        }
    }
    let mut pal = Vec::new();
    if let Some(p) = &a.palette {
        for &[r, g, b] in p {
            pal.extend_from_slice(&[b, g, r, 0]);
        }
    }
    let mask_bytes = if a.dib_size == 40 && has_masks {
        let m = a
            .masks
            .unwrap_or([0x00FF_0000, 0x0000_FF00, 0x0000_00FF, 0xFF00_0000]);
        let n = if a.compression == 6 { 4 } else { 3 };
        m[..n]
            .iter()
            .flat_map(|v| v.to_le_bytes())
            .collect::<Vec<u8>>()
    } else {
        Vec::new()
    };
    let data_offset = 14 + a.dib_size as usize + mask_bytes.len() + pal.len() + a.pad;
    let size = 14 + dib.len() + mask_bytes.len() + pal.len() + a.pad + a.pixel.len();

    let mut v = Vec::with_capacity(size);
    v.extend_from_slice(b"BM");
    le32(&mut v, size as u32);
    le16(&mut v, 0);
    le16(&mut v, 0);
    le32(&mut v, data_offset as u32);
    v.extend_from_slice(&dib);
    v.extend_from_slice(&mask_bytes);
    v.extend_from_slice(&pal);
    v.extend(std::iter::repeat_n(0xAA, a.pad));
    v.extend_from_slice(a.pixel);
    v
}

/// RLE8 stream assembler: `("enc", n, idx)`, `("abs", bytes)`,
/// `("eol",)`, `("delta", dx, dy)`, `("eof",)`.
enum Rle {
    Enc(u8, u8),
    Abs(&'static [u8]),
    Eol,
    Delta(u8, u8),
    Eof,
}

fn rle8_stream(ops: &[Rle]) -> Vec<u8> {
    let mut out = Vec::new();
    for op in ops {
        match op {
            Rle::Enc(n, idx) => out.extend_from_slice(&[*n, *idx]),
            Rle::Abs(run) => {
                out.extend_from_slice(&[0, run.len() as u8]);
                out.extend_from_slice(run);
                if run.len() % 2 == 1 {
                    out.push(0);
                }
            }
            Rle::Eol => out.extend_from_slice(&[0, 0]),
            Rle::Delta(dx, dy) => out.extend_from_slice(&[0, 2, *dx, *dy]),
            Rle::Eof => out.extend_from_slice(&[0, 1]),
        }
    }
    out
}

// ---- the shared pixel matrix -----------------------------------------------

const W: u32 = 5;
const H: u32 = 4;

/// The matrix every fixture encodes: `(r, g, b)` with distinct channel
/// formulas so a swapped channel or wrong offset cannot hide.
fn matrix(x: u32, y: u32) -> [u8; 3] {
    [
        ((x * 37 + y * 11) % 256) as u8,
        ((x * 19 + y * 53) % 256) as u8,
        ((x * 71 + y * 29) % 256) as u8,
    ]
}

fn assert_pixels(img: &Image<Rgba, u8>, alpha: u8) {
    assert_eq!(img.width(), W);
    assert_eq!(img.height(), H);
    for y in 0..H {
        for x in 0..W {
            let [r, g, b] = matrix(x, y);
            let want = [r, g, b, alpha];
            assert_eq!(img.pixel(x, y), Some(&want[..]), "pixel ({x},{y})");
        }
    }
}

/// Rows stored `B G R` per pixel, padded to 4-byte alignment; `top_down`
/// controls write order.
fn bgr_rows(top_down: bool) -> Vec<u8> {
    let mut v = Vec::new();
    let order: Vec<u32> = if top_down {
        (0..H).collect()
    } else {
        (0..H).rev().collect()
    };
    for y in order {
        let mut row = Vec::new();
        for x in 0..W {
            let [r, g, b] = matrix(x, y);
            row.extend_from_slice(&[b, g, r]);
        }
        while row.len() % 4 != 0 {
            row.push(0);
        }
        v.extend_from_slice(&row);
    }
    v
}

/// Rows stored `B G R A` per pixel (4-byte aligned already).
fn bgra_rows(top_down: bool, alpha: u8) -> Vec<u8> {
    let mut v = Vec::new();
    let order: Vec<u32> = if top_down {
        (0..H).collect()
    } else {
        (0..H).rev().collect()
    };
    for y in order {
        for x in 0..W {
            let [r, g, b] = matrix(x, y);
            v.extend_from_slice(&[b, g, r, alpha]);
        }
    }
    v
}

/// Rows stored as 5-bit channels under masks `0x7C00/0x03E0/0x001F`
/// (R,G,B) packed into u32 pixels, like a real 1555 file.
fn xrgb1555_rows() -> Vec<u8> {
    let mut v = Vec::new();
    for y in (0..H).rev() {
        for x in 0..W {
            let [r, g, b] = matrix(x, y);
            let word = (u32::from(r >> 3) << 10) | (u32::from(g >> 3) << 5) | u32::from(b >> 3);
            v.extend_from_slice(&word.to_le_bytes());
        }
    }
    v
}

fn gray_palette() -> Vec<[u8; 3]> {
    (0..=255u8).map(|i| [i, i, i]).collect()
}

/// The RLE8 ops the `rle8.bmp` fixture encodes (6x4, palette index =
/// gray value):
///
/// ```text
/// 1 1 1 2 3 4
/// 0 0 9 9 0 0
/// 0 7 7 7 0 0
/// 5 0 0 0 8 8
/// ```
fn rle8_ops() -> Vec<Rle> {
    vec![
        // Absolute runs need n>=3: n<3 collides with EOL/EOF/delta.
        Rle::Enc(1, 5),
        Rle::Enc(3, 0),
        Rle::Enc(2, 8),
        Rle::Eol,
        Rle::Delta(1, 0),
        Rle::Enc(3, 7),
        Rle::Eol,
        Rle::Enc(2, 0),
        Rle::Enc(2, 9),
        Rle::Eol,
        Rle::Enc(3, 1),
        Rle::Abs(&[2, 3, 4]),
        Rle::Eof,
    ]
}

fn rle8_bmp(stream: &[u8]) -> Vec<u8> {
    build_bmp(&BmpArgs {
        w: 6,
        h: 4,
        bpp: 8,
        compression: 1,
        dib_size: 40,
        masks: None,
        palette: Some(gray_palette()),
        colors_used: 0,
        pixel: stream,
        pad: 0,
    })
}

fn fixture(name: &str) -> Vec<u8> {
    let path = format!("{}/tests/fixtures/bmp/{name}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read(path).expect("fixture file must exist; run gen_fixtures.py")
}

// ---- fixture cross-checks ---------------------------------------------------

/// The Rust builders and the Python generator must produce identical
/// bytes for every fixture on disk.
#[test]
fn builders_match_fixture_files() {
    let cases: Vec<(&str, Vec<u8>)> = vec![
        (
            "p24_bottom_up.bmp",
            build_bmp(&BmpArgs {
                w: 5,
                h: 4,
                bpp: 24,
                compression: 0,
                dib_size: 40,
                masks: None,
                palette: None,
                colors_used: 0,
                pixel: &bgr_rows(false),
                pad: 0,
            }),
        ),
        (
            "p24_top_down.bmp",
            build_bmp(&BmpArgs {
                w: 5,
                h: -4,
                bpp: 24,
                compression: 0,
                dib_size: 40,
                masks: None,
                palette: None,
                colors_used: 0,
                pixel: &bgr_rows(true),
                pad: 0,
            }),
        ),
        (
            "p32_bitfields.bmp",
            build_bmp(&BmpArgs {
                w: 5,
                h: 4,
                bpp: 32,
                compression: 3,
                dib_size: 40,
                masks: Some([0x00FF_0000, 0x0000_FF00, 0x0000_00FF, 0xFF00_0000]),
                palette: None,
                colors_used: 0,
                pixel: &bgra_rows(false, 0x40),
                pad: 0,
            }),
        ),
        (
            "p32_x1555.bmp",
            build_bmp(&BmpArgs {
                w: 5,
                h: 4,
                bpp: 32,
                compression: 3,
                dib_size: 40,
                masks: Some([0x0000_7C00, 0x0000_03E0, 0x0000_001F, 0]),
                palette: None,
                colors_used: 0,
                pixel: &xrgb1555_rows(),
                pad: 0,
            }),
        ),
        (
            "p32_v4_header.bmp",
            build_bmp(&BmpArgs {
                w: 5,
                h: 4,
                bpp: 32,
                compression: 3,
                dib_size: 108,
                masks: Some([0x00FF_0000, 0x0000_FF00, 0x0000_00FF, 0xFF00_0000]),
                palette: None,
                colors_used: 0,
                pixel: &bgra_rows(false, 0x40),
                pad: 0,
            }),
        ),
        (
            "p32_v5_rgb.bmp",
            build_bmp(&BmpArgs {
                w: 5,
                h: 4,
                bpp: 32,
                compression: 0,
                dib_size: 124,
                masks: None,
                palette: None,
                colors_used: 0,
                pixel: &bgra_rows(false, 0x99),
                pad: 0,
            }),
        ),
        ("rle8.bmp", rle8_bmp(&rle8_stream(&rle8_ops()))),
    ];
    for (name, built) in cases {
        assert_eq!(built, fixture(name), "{name}: builder drifted from fixture");
    }
}

// ---- known-pixel decodes ----------------------------------------------------

#[test]
fn decodes_24bit_bottom_up() {
    let img = decode(&fixture("p24_bottom_up.bmp")).unwrap();
    assert_pixels(&img, 255);
}

#[test]
fn decodes_24bit_top_down() {
    let img = decode(&fixture("p24_top_down.bmp")).unwrap();
    assert!(info(&fixture("p24_top_down.bmp")).unwrap().top_down);
    assert_pixels(&img, 255);
}

#[test]
fn decodes_32bit_bitfields_opaque_without_alpha_mask() {
    // A 40-byte BI_BITFIELDS header carries only 3 inline masks, so
    // there is no alpha channel: pixels are opaque and the fourth byte
    // is dead data.
    let img = decode(&fixture("p32_bitfields.bmp")).unwrap();
    assert_pixels(&img, 255);
}

#[test]
fn decodes_32bit_five_bit_channel_masks() {
    // Masks 0x7C00/0x03E0/0x001F: quantized 5-bit channels must scale
    // back to u8 with round-half-up, not just shift-left.
    let img = decode(&fixture("p32_x1555.bmp")).unwrap();
    // Literal pins for pixel (1,0): R=37>>3=4 → (4*255+15)/31 = 33,
    // G=19>>3=2 → 16, B=71>>3=8 → 66.
    assert_eq!(img.pixel(1, 0), Some(&[33, 16, 66, 255][..]));
    for y in 0..H {
        for x in 0..W {
            let [r, g, b] = matrix(x, y);
            let s5 = |v: u8| -> u8 {
                let v5 = u64::from(v >> 3);
                ((v5 * 255 + 15) / 31) as u8
            };
            assert_eq!(
                img.pixel(x, y),
                Some(&[s5(r), s5(g), s5(b), 255][..]),
                "({x},{y})"
            );
        }
    }
}

#[test]
fn decodes_v4_header_with_alpha() {
    let img = decode(&fixture("p32_v4_header.bmp")).unwrap();
    assert_pixels(&img, 0x40);
    assert_eq!(
        info(&fixture("p32_v4_header.bmp")).unwrap().dib_header_size,
        108
    );
}

#[test]
fn decodes_v5_rgb_alpha_byte_is_padding() {
    // BI_RGB 32-bit has no alpha channel: the 4th byte is padding and
    // every pixel is opaque, per Windows GDI semantics.
    let img = decode(&fixture("p32_v5_rgb.bmp")).unwrap();
    assert_pixels(&img, 255);
    let i = info(&fixture("p32_v5_rgb.bmp")).unwrap();
    assert_eq!(i.dib_header_size, 124);
    assert_eq!(i.compression, Compression::Rgb);
}

#[test]
fn decodes_rle8_all_modes() {
    let img = decode(&fixture("rle8.bmp")).unwrap();
    assert_eq!((img.width(), img.height()), (6, 4));
    let want = [
        [1u8, 1, 1, 2, 3, 4],
        [0, 0, 9, 9, 0, 0],
        [0, 7, 7, 7, 0, 0],
        [5, 0, 0, 0, 8, 8],
    ];
    for y in 0..4u32 {
        for x in 0..6u32 {
            let g = want[y as usize][x as usize];
            assert_eq!(img.pixel(x, y), Some(&[g, g, g, 255][..]), "({x},{y})");
        }
    }
}

/// A palette index outside `colors_used` is an error, not a guess.
#[test]
fn rle8_palette_index_out_of_range_colors_used() {
    // Only 4 palette entries loaded (colors_used=4); index 5 must error.
    let bmp = build_bmp(&BmpArgs {
        w: 6,
        h: 4,
        bpp: 8,
        compression: 1,
        dib_size: 40,
        masks: None,
        palette: Some(gray_palette()[..4].to_vec()),
        colors_used: 4,
        pixel: &rle8_stream(&[Rle::Enc(2, 5), Rle::Eof]),
        pad: 0,
    });
    assert!(matches!(decode(&bmp), Err(Error::BadValue(_))));
}

// ---- round-trip through a minimal writer ------------------------------------

/// Minimal 24-bit writer: the inverse of `decode` for `BI_RGB`.
fn write_24(img: &Image<Rgba, u8>) -> Vec<u8> {
    let w = img.width() as usize;
    let stride = (w * 3 + 3) & !3;
    let mut pixel = vec![0u8; stride * img.height() as usize];
    for y in (0..img.height()).rev() {
        let row = (img.height() - 1 - y) as usize;
        for x in 0..w {
            let p = img.pixel(x as u32, y).unwrap();
            let q = row * stride + x * 3;
            pixel[q] = p[2];
            pixel[q + 1] = p[1];
            pixel[q + 2] = p[0];
        }
    }
    build_bmp(&BmpArgs {
        w: img.width() as i32,
        h: img.height() as i32,
        bpp: 24,
        compression: 0,
        dib_size: 40,
        masks: None,
        palette: None,
        colors_used: 0,
        pixel: &pixel,
        pad: 0,
    })
}

/// `decode(write(img)) == img` for widths that need 0–3 padding bytes.
#[test]
fn round_trip_24bit_writer() {
    for w in 1..=8u32 {
        let h = 3u32;
        let mut px = Vec::with_capacity((w * h) as usize);
        for y in 0..h {
            for x in 0..w {
                let [r, g, b] = matrix(x, y);
                px.push([r, g, b, 255]);
            }
        }
        let img = Image::<Rgba, u8>::from_vec(w, h, px.into_iter().flatten().collect()).unwrap();
        let bytes = write_24(&img);
        let back = decode(&bytes).unwrap();
        assert_eq!(back.as_slice(), img.as_slice(), "w={w}");
    }
}

// ---- RLE8 semantics ---------------------------------------------------------

/// A stream with no EOF escape still decodes; unwritten pixels get
/// palette index 0 (the background convention).
#[test]
fn rle8_implicit_eof_fills_background() {
    // Only y=0 written: bottom row 7,7,7,7,?,? where x=4,5 stay 0.
    let bmp = rle8_bmp(&rle8_stream(&[Rle::Enc(4, 7)]));
    let img = decode(&bmp).unwrap();
    assert_eq!(img.pixel(0, 3), Some(&[7, 7, 7, 255][..]));
    assert_eq!(img.pixel(3, 3), Some(&[7, 7, 7, 255][..]));
    assert_eq!(img.pixel(4, 3), Some(&[0, 0, 0, 255][..]));
    assert_eq!(img.pixel(0, 0), Some(&[0, 0, 0, 255][..]));
}

/// A delta that lands exactly on the far edge is legal — nothing writes
/// there, so `x == w`/`y == h` are in bounds.
#[test]
fn rle8_delta_to_edge_then_eof() {
    let bmp = rle8_bmp(&rle8_stream(&[Rle::Delta(6, 4), Rle::Eof]));
    let img = decode(&bmp).unwrap();
    assert_eq!(img.pixel(0, 0), Some(&[0, 0, 0, 255][..]));
}

/// A delta past the edge is malformed, not clipped.
#[test]
fn rle8_delta_past_edge_errors() {
    let bmp = rle8_bmp(&rle8_stream(&[Rle::Delta(7, 0), Rle::Eof]));
    assert!(matches!(decode(&bmp), Err(Error::BadValue(_))));
    let bmp = rle8_bmp(&rle8_stream(&[Rle::Delta(0, 5), Rle::Eof]));
    assert!(matches!(decode(&bmp), Err(Error::BadValue(_))));
}

/// An encoded run that runs off the right edge errors rather than
/// silently wrapping into the next row.
#[test]
fn rle8_run_past_row_errors() {
    let bmp = rle8_bmp(&rle8_stream(&[Rle::Enc(7, 1), Rle::Eof]));
    assert!(matches!(decode(&bmp), Err(Error::BadValue(_))));
}

/// A palette index outside `colors_used` is an error, not a guess.
#[test]
fn rle8_palette_index_out_of_range() {
    // Only 4 palette entries loaded (colors_used=4); index 5 must error.
    let bmp = build_bmp(&BmpArgs {
        w: 6,
        h: 4,
        bpp: 8,
        compression: 1,
        dib_size: 40,
        masks: None,
        palette: Some(gray_palette()[..4].to_vec()),
        colors_used: 4,
        pixel: &rle8_stream(&[Rle::Enc(2, 5), Rle::Eof]),
        pad: 0,
    });
    assert!(matches!(decode(&bmp), Err(Error::BadValue(_))));
}

/// An absolute run cut off by physical end-of-input is truncated.
#[test]
fn rle8_absolute_run_truncated() {
    let mut stream = rle8_stream(&[Rle::Enc(1, 1)]);
    stream.extend_from_slice(&[0, 10, 5, 5]); // declares 10, gives 2
    let bmp = rle8_bmp(&stream);
    assert!(matches!(decode(&bmp), Err(Error::Truncated { .. })));
}

/// Palette "reserved" bytes are never read as alpha.
#[test]
fn rle8_palette_reserved_byte_is_not_alpha() {
    let mut palette = vec![[9u8, 8, 7]];
    palette.extend_from_slice(&[[0, 0, 0]; 255]);
    let mut bmp = build_bmp(&BmpArgs {
        w: 1,
        h: 1,
        bpp: 8,
        compression: 1,
        dib_size: 40,
        masks: None,
        palette: Some(palette.clone()),
        colors_used: 0,
        pixel: &rle8_stream(&[Rle::Enc(1, 0), Rle::Eof]),
        pad: 0,
    });
    // Set the reserved byte of entry 0 to 0x77: alpha must stay 255.
    bmp[54 + 3] = 0x77;
    let img = decode(&bmp).unwrap();
    assert_eq!(img.pixel(0, 0), Some(&[9, 8, 7, 255][..]));
    palette.clear();
}

/// Top-down RLE8 is not a legal file, even though the header parses.
#[test]
fn rle8_top_down_rejected() {
    let bmp = build_bmp(&BmpArgs {
        w: 6,
        h: -4,
        bpp: 8,
        compression: 1,
        dib_size: 40,
        masks: None,
        palette: Some(gray_palette()),
        colors_used: 0,
        pixel: &rle8_stream(&[Rle::Eof]),
        pad: 0,
    });
    assert!(matches!(decode(&bmp), Err(Error::BadValue(_))));
}

// ---- header handling --------------------------------------------------------

/// `bfSize` is advisory only: a wrong value still decodes.
#[test]
fn stale_file_size_field_ignored() {
    let mut bmp = fixture("p24_bottom_up.bmp");
    bmp[2..6].copy_from_slice(&123_456u32.to_le_bytes());
    let img = decode(&bmp).unwrap();
    assert_pixels(&img, 255);
}

/// `bfOffBits` may skip padding bytes between structures and pixels.
#[test]
fn data_offset_with_padding_gap() {
    let bmp = build_bmp(&BmpArgs {
        w: 5,
        h: 4,
        bpp: 24,
        compression: 0,
        dib_size: 40,
        masks: None,
        palette: None,
        colors_used: 0,
        pixel: &bgr_rows(false),
        pad: 16,
    });
    let img = decode(&bmp).unwrap();
    assert_pixels(&img, 255);
}

/// `bfOffBits` landing inside the palette is malformed.
#[test]
fn data_offset_inside_palette_rejected() {
    let mut bmp = rle8_bmp(&rle8_stream(&[Rle::Eof]));
    bmp[10..14].copy_from_slice(&60u32.to_le_bytes()); // inside palette
    assert!(matches!(decode(&bmp), Err(Error::BadValue(_))));
}

/// The final row's pad bytes may be absent.
#[test]
fn missing_final_row_padding_decodes() {
    let full = fixture("p24_bottom_up.bmp");
    // 24bpp width 5: row bytes 15, stride 16. Drop the last pad byte.
    let truncated_file = &full[..full.len() - 1];
    let img = decode(truncated_file).unwrap();
    assert_pixels(&img, 255);
}

/// A file that ends mid-row is truncated, not zero-padded.
#[test]
fn mid_row_truncation_errors() {
    let full = fixture("p24_bottom_up.bmp");
    let half = &full[..full.len() - 4];
    assert!(matches!(decode(half), Err(Error::Truncated { .. })));
}

/// Non-contiguous and overlapping masks are malformed.
#[test]
fn bad_channel_masks_rejected() {
    // (rgb_masks, file carries a 4th inline mask?, expect ok)
    let cases: &[([u32; 4], u32, bool)] = &[
        ([0x00FF_00FF, 0x0000_FF00, 0x0000_00FF, 0], 3, false), // hole in R
        ([0x00FF_0000, 0x00FF_0000, 0x0000_00FF, 0], 3, false), // R==G overlap
        ([0, 0x0000_FF00, 0x0000_00FF, 0], 3, false),           // absent R
        (
            [0x00FF_0000, 0x0000_FF00, 0x0000_00FF, 0x00FF_0000],
            6,
            false,
        ), // A overlaps R
        (
            [0x00FF_0000, 0x0000_FF00, 0x0000_00FF, 0xFF00_0000],
            6,
            true,
        ), // sane ARGB
    ];
    for &(masks, comp, ok) in cases {
        let bmp = build_bmp(&BmpArgs {
            w: 5,
            h: 4,
            bpp: 32,
            compression: comp,
            dib_size: 40,
            masks: Some(masks),
            palette: None,
            colors_used: 0,
            pixel: &bgra_rows(false, 0x40),
            pad: 0,
        });
        assert_eq!(decode(&bmp).is_ok(), ok, "masks {masks:?}");
    }
}

/// `BI_ALPHABITFIELDS` carries a fourth inline mask after a 40-byte
/// header and must decode with real alpha.
#[test]
fn alphabitfields_infoheader_decodes() {
    let bmp = build_bmp(&BmpArgs {
        w: 5,
        h: 4,
        bpp: 32,
        compression: 6,
        dib_size: 40,
        masks: Some([0x00FF_0000, 0x0000_FF00, 0x0000_00FF, 0xFF00_0000]),
        palette: None,
        colors_used: 0,
        pixel: &bgra_rows(false, 0x40),
        pad: 0,
    });
    let img = decode(&bmp).unwrap();
    assert_pixels(&img, 0x40);
}

/// Everything outside scope is a named refusal, never a mis-decode.
#[test]
fn unsupported_variants_are_named_errors() {
    // Not a BMP at all.
    assert!(matches!(decode(b"ZZ"), Err(Error::Truncated { .. })));
    let mut bad_magic = fixture("p24_bottom_up.bmp");
    bad_magic[0] = b'Z';
    assert!(matches!(
        decode(&bad_magic),
        Err(Error::InvalidMagic { .. })
    ));

    // OS/2 signatures are real bitmaps we don't implement.
    let mut os2 = fixture("p24_bottom_up.bmp");
    os2[..2].copy_from_slice(b"CI");
    assert!(matches!(decode(&os2), Err(Error::Unsupported(_))));

    // BITMAPCOREHEADER (12-byte DIB).
    let mut core = fixture("p24_bottom_up.bmp");
    core[14..18].copy_from_slice(&12u32.to_le_bytes());
    assert!(matches!(decode(&core), Err(Error::Unsupported(_))));

    // Unsupported depths and compressions via header surgery.
    for (bpp, comp, what) in [
        (16u16, 0u32, "16-bit"),
        (1, 0, "1-bit"),
        (4, 0, "4-bit"),
        (24, 3, "24-bit bitfields"),
        (8, 0, "uncompressed 8-bit"),
        (24, 1, "RLE8 on 24-bit"),
        (24, 2, "RLE4"),
        (24, 4, "JPEG"),
        (24, 5, "PNG"),
        (24, 99, "unknown compression"),
    ] {
        let mut bmp = fixture("p24_bottom_up.bmp");
        bmp[28..30].copy_from_slice(&bpp.to_le_bytes());
        bmp[30..34].copy_from_slice(&comp.to_le_bytes());
        assert!(decode(&bmp).is_err(), "{what}: bpp={bpp} comp={comp}");
    }
}

/// Semantic impossibilities are `BadValue`; they must not allocate.
#[test]
fn hostile_header_values_rejected() {
    let mut bmp = fixture("p24_bottom_up.bmp");
    bmp[18..22].copy_from_slice(&0i32.to_le_bytes()); // width 0
    assert!(matches!(decode(&bmp), Err(Error::BadValue(_))));

    let mut bmp = fixture("p24_bottom_up.bmp");
    bmp[22..26].copy_from_slice(&0i32.to_le_bytes()); // height 0
    assert!(matches!(decode(&bmp), Err(Error::BadValue(_))));

    let mut bmp = fixture("p24_bottom_up.bmp");
    bmp[22..26].copy_from_slice(&i32::MIN.to_le_bytes()); // height overflow
    assert!(matches!(decode(&bmp), Err(Error::BadValue(_))));

    let mut bmp = fixture("p24_bottom_up.bmp");
    bmp[26..28].copy_from_slice(&2u16.to_le_bytes()); // planes 2
    assert!(matches!(decode(&bmp), Err(Error::BadValue(_))));

    // Declared size over the raster ceiling → TooLarge, before a byte
    // of pixel data is considered.
    let mut huge = fixture("p24_bottom_up.bmp");
    huge[18..22].copy_from_slice(&50_000u32.to_le_bytes());
    huge[22..26].copy_from_slice(&50_000u32.to_le_bytes());
    assert!(matches!(decode(&huge), Err(Error::TooLarge { .. })));

    // bfOffBits past EOF.
    let mut bmp = fixture("p24_bottom_up.bmp");
    bmp[10..14].copy_from_slice(&0xFFFF_F000u32.to_le_bytes());
    assert!(matches!(decode(&bmp), Err(Error::Truncated { .. })));

    // bfOffBits inside the DIB header itself.
    let mut bmp = fixture("p24_bottom_up.bmp");
    bmp[10..14].copy_from_slice(&20u32.to_le_bytes());
    assert!(matches!(decode(&bmp), Err(Error::BadValue(_))));
}

// ---- hostile input: no panic, ever ------------------------------------------

/// Every prefix of every fixture decodes or errors — never panics.
#[test]
fn prefix_scan_never_panics() {
    for name in [
        "p24_bottom_up.bmp",
        "p24_top_down.bmp",
        "p32_bitfields.bmp",
        "p32_x1555.bmp",
        "p32_v4_header.bmp",
        "p32_v5_rgb.bmp",
        "rle8.bmp",
    ] {
        let f = fixture(name);
        for n in 0..f.len() {
            let _ = decode(&f[..n]);
            let _ = info(&f[..n]);
        }
    }
}

/// 10 000 deterministic single-byte corruptions across all fixtures:
/// any outcome is fine as long as it is not a panic.
#[test]
fn ten_thousand_mutations_never_panic() {
    let mut rng = SplitMix64::new(0xB3D5_EED5_0000_1234);
    let names = [
        "p24_bottom_up.bmp",
        "p32_bitfields.bmp",
        "p32_x1555.bmp",
        "p32_v5_rgb.bmp",
        "rle8.bmp",
    ];
    for _ in 0..10_000 {
        let f = fixture(names[(rng.next_u64() as usize) % names.len()]);
        let mut m = f.clone();
        let pos = (rng.next_u64() as usize) % m.len();
        m[pos] ^= (rng.next_u64() as u8) | 1;
        let _ = decode(&m);
    }
}

/// Wholly synthetic garbage never panics either.
#[test]
fn synthetic_garbage_never_panics() {
    let mut rng = SplitMix64::new(0xBADC_0FFE_E0DD_F00D);
    let mut buf = vec![0u8; 256];
    for _ in 0..2_000 {
        rng.fill_bytes(&mut buf[..]);
        let _ = decode(&buf);
    }
}
