//! `box_average` against hand-computed buffers. Every expected byte is
//! derived on paper from the integer-boundary convention in
//! `docs/algorithms/raster.md`; none of it is generated by the code under
//! test.

use pith_digest::Error;
use pith_image::raster::{Gray, Image, Rgb, box_average};

/// 4×4 gray ramp 0..=15.
fn ramp4() -> Image<Gray> {
    Image::from_vec(4, 4, (0u8..16).collect()).unwrap()
}

#[test]
fn downscale_4x4_to_2x2_is_exact_2x2_box_means() {
    let out = box_average(&ramp4(), 2, 2).unwrap();
    // Boxes are the four 2×2 quadrants:
    //   [0,1,4,5] -> 5/2 = 2.5  -> 3 (half up)
    //   [2,3,6,7] -> 18/4 = 4.5 -> 5
    //   [8,9,12,13] -> 42/4 = 10.5 -> 11
    //   [10,11,14,15] -> 50/4 = 12.5 -> 13
    assert_eq!((out.width(), out.height()), (2, 2));
    assert_eq!(out.as_slice(), &[3, 5, 11, 13]);
}

#[test]
fn downscale_3x3_to_2x2_uses_floor_boundaries() {
    // 3->2 boundaries: [⌊0⌋,⌊1⌋) and [⌊3/2⌋=1,⌊6/2⌋=3) -> widths 1 and 2.
    let im: Image<Gray> = Image::from_vec(3, 3, vec![1, 2, 3, 4, 5, 6, 7, 8, 9]).unwrap();
    let out = box_average(&im, 2, 2).unwrap();
    // rows [0,1) x cols [0,1): {1}                    -> 1
    // rows [0,1) x cols [1,3): {2,3}                 -> 2.5 -> 3
    // rows [1,3) x cols [0,1): {4,7}                 -> 5.5 -> 6
    // rows [1,3) x cols [1,3): {5,6,8,9} -> 28/4 = 7 -> 7
    assert_eq!(out.as_slice(), &[1, 3, 6, 7]);
}

#[test]
fn shrink_to_1x1_is_the_exact_mean() {
    // Mean of 0..=15 is 120/16 = 7.5 -> 8 half-up.
    let out = box_average(&ramp4(), 1, 1).unwrap();
    assert_eq!((out.width(), out.height()), (1, 1));
    assert_eq!(out.as_slice(), &[8]);

    // Odd count with a known fractional part: [0,10,20] -> 30/3 = 10.
    let row: Image<Gray> = Image::from_vec(3, 1, vec![0, 10, 20]).unwrap();
    assert_eq!(box_average(&row, 1, 1).unwrap().as_slice(), &[10]);
}

#[test]
fn constant_images_resample_to_the_constant() {
    // The spec's idempotence property: a constant plane has every box
    // mean equal to the constant, at any output size.
    let im: Image<Rgb> = Image::from_vec(4, 4, vec![77u8; 48]).unwrap();
    for &(w, h) in &[(1u32, 1u32), (2, 2), (3, 2), (4, 4), (7, 5)] {
        let out = box_average(&im, w, h).unwrap();
        assert_eq!((out.width(), out.height()), (w, h));
        assert!(
            out.as_slice().iter().all(|&s| s == 77),
            "{w}x{h} changed a constant image"
        );
    }
}

#[test]
fn resize_to_same_size_is_identity() {
    let im = ramp4();
    let out = box_average(&im, 4, 4).unwrap();
    assert_eq!(out.as_slice(), im.as_slice());
}

#[test]
fn averaging_is_per_channel() {
    // 2×1 RGB -> 1×1: each channel averages independently.
    let im: Image<Rgb> = Image::from_vec(2, 1, vec![10, 20, 30, 40, 51, 60]).unwrap();
    let out = box_average(&im, 1, 1).unwrap();
    // R: 50/2 = 25, G: 71/2 = 35.5 -> 36 (half up), B: 90/2 = 45.
    assert_eq!(out.as_slice(), &[25, 36, 45]);
}

#[test]
fn upscale_collapses_to_nearest_sample() {
    // 2×2 -> 4×4: every output box is empty, so each samples the source
    // pixel at its box centre — exact 2× replication.
    let im: Image<Gray> = Image::from_vec(2, 2, vec![1, 2, 3, 4]).unwrap();
    let out = box_average(&im, 4, 4).unwrap();
    assert_eq!(
        out.as_slice(),
        &[1, 1, 2, 2, 1, 1, 2, 2, 3, 3, 4, 4, 3, 3, 4, 4]
    );
}

#[test]
fn asymmetric_downscale_averages_one_axis_only() {
    // 4×1 -> 2×1: two horizontal 2-wide boxes, no vertical averaging.
    let im: Image<Gray> = Image::from_vec(4, 1, vec![10, 20, 30, 41]).unwrap();
    let out = box_average(&im, 2, 1).unwrap();
    // {10,20} -> 15 ; {30,41} -> 71/2 = 35.5 -> 36.
    assert_eq!(out.as_slice(), &[15, 36]);
}

#[test]
fn zero_output_dimension_is_bad_value() {
    let im = ramp4();
    assert!(matches!(box_average(&im, 0, 4), Err(Error::BadValue(_))));
    assert!(matches!(box_average(&im, 4, 0), Err(Error::BadValue(_))));
}

#[test]
fn u16_samples_round_through_the_same_rule() {
    let im: Image<Gray, u16> = Image::from_vec(2, 1, vec![1000u16, 1001]).unwrap();
    let out = box_average(&im, 1, 1).unwrap();
    // 2001/2 = 1000.5 -> 1001 half-up.
    assert_eq!(out.as_slice(), &[1001]);
}
